# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('quote_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Reservation')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_pick_up', models.TextField(blank=True, null=True)),
                ('location_drop_off', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Reservation')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('charge_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
