# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='happening',
            field=models.BooleanField(default=False),
        ),
    ]
