# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20171104_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
