# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20171105_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_desription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
