# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='comments',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='location_drop_off',
            field=models.TextField(blank=True, default='here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='location_pick_up',
            field=models.TextField(blank=True, default='there'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
