# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20171106_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(verbose_name='Number of hours'),
        ),
    ]
